### ISSUE TITLE
Cerberus deleting keys when error at Cerberus server

### ISSUE THREAD

**Issue by NamespaceValentine** [Nike-Inc/cerberus-archaius-client#2]
In the case of the FixedDelayPollingScheduler, where ignoreDeletesFromSource is set to false, when Cerberus cannot be contacted (for instance due to the auth servers being down), all keys are deleted. This is unexpected behavior. I would like to request that when an error comes back from cerberus regarding decryption or authentication, that keys not be deleted, but only in the case that cerberus successfully returns an object that has deleted keys.

**Comment by tlisonbee** [comment]
Thanks, yes, this makes sense.  I believe the change needed is in the poll method in NamespacedCerberusConfigurationSource.  It looks like an easy change but it will take me a little while to test it.

**Comment by tlisonbee** [comment]
This issue has been fixed in v2.0.0.
